Module3 task1
htmlacademy-react/938431-six-cities-7 pull request #5
Opened 2021-06-19 17:28 UTC by lula-may

Егор, привет!
Задержалась с этим заданием, предыдущая неделя у меня полностью вылетела. Теперь придется догонять.
В описании задания много было неясного, так что не уверена, что правильно поняла, и сделала то, что нужно.
Если у тебя будут замечания, (надеюсь на это), то может быть созвон устроим?

2021-06-20 15:24 UTC, eoL95 commented on project/src/components/comment-form/comment-form.jsx
> +      onSubmit={(evt) => {
Функцию обработчик лучше заворачивать в useCallback, чтобы не пересоздавать функцию на каждый рендер компонента.

2021-06-20 16:35 UTC, eoL95 requested changes
Привет, Юля! В целом все достаточно неплохо. Но есть ошибки, и, видимо недопонимание с роутингом. Давай созвонимся и обсудим. В какой день и время тебе удобно?

2021-06-21 20:23 UTC, lula-may commented on project/src/components/offer-card/offer-card.jsx
> +  const ratingStyle = getRatingStyle(rating);
Егор, я внесла исправления по твоим замечаниям. Но, созваниваться будем, как договорились.

2021-06-23 15:10 UTC, eoL95 commented on project/src/utils.js
> +const cn = (...args) => args.join(' ');
Тут ошибка. false не должен попадать в список
![image](https://user-images.githubusercontent.com/22622869/123121896-36fcb200-d44e-11eb-8c01-ecbbc5bcc748.png)

2021-06-23 15:22 UTC, lula-may commented on project/src/utils.js
> +const cn = (...args) => args.join(' ');
ААаа, видела, даже хотела тебя спрашивать об этом.

2021-06-23 21:12 UTC, merged