Module4 task1
htmlacademy-react/938431-six-cities-7 pull request #6
Opened 2021-06-25 20:53 UTC by lula-may

Егор, привет!
Вот, подкидываю тебе работенку))
Ничего серьезного сказать не могу) Буду ждать твоих комментариев, если будут)

2021-06-27 14:13 UTC, lula-may commented
Егор, поскольку ты еще не успел взять задание на проверку, я решила залить в этот пулреквест коммиты по следующему заданию. Учитывая, что бОльшую часть задания 4.2 я сделала в 3-м модуле, изменений совсем немного.

2021-06-27 15:49 UTC, lula-may commented
Все-таки не совсем понятно, как лучше организовать код для рендера списка карточек.
Этот список есть на 3-х страницах: главной, странице Комнаты и на странице Избранного.
Какие есть отличия:

1. Классы, причем не только у обертки, но и у внутренних тегов;
2. Только для карточки на главной странице нужен обработчик наведения - просится какая-то обертка для навешивания этого обработчика.
3. У карточки со страницы избранного для картинки берется `url `из свойства `previewImage`, хотя здесь я не уверена, может быть для карточек на всех страницах надо брать картинку отсюда, а я почему-то решила, что для больших карточек нужно брать `url `из первого элемента поля `images`, но даже если брать `url `для всех из поля `previewImage`, в разметке атрибуты `width `и `height `- разные.
4. В карточке со страницы Избраное не рендерится маркер `Premium`.

2021-06-28 07:36 UTC, eoL95 requested changes

2021-06-28 07:36 UTC, eoL95 commented on project/src/components/offer-card/offer-card.jsx
> +  const handleMouseLeave = useCallback(() => onCardLeave && onCardLeave(null), [onCardLeave]);
onCardLeave не должен зависеть от того что в него передают. Нужно в основном компоненте, где он передается сбрасывать в null.

2021-06-28 07:36 UTC, eoL95 commented on project/src/components/map/map.jsx
> +  const defaultIcon = leaflet.icon({
Эти иконки можно создать снаружи компонента, иначе они будут пересоздаваться на каждый рендер.

2021-06-28 07:36 UTC, eoL95 commented on project/src/components/offer-card-default/offer-card-default.jsx
> +  const {offer, type, ...restProps} = props;
Давай все-таки попробуем ограничиться одним компонентом OfferCard, и полностью управлять им через пропсы

2021-06-28 07:37 UTC, eoL95 commented
По поводу карточек
1) Классы на разных страницах можно передать в пропсы.
2) Если передан пропс обработчика - то выполнять функцию, если нет - то не выполнять,  никакой обертки не нужно.
3) Картинку можно унести внутрь основного компонента, высоту и ширину передавать через пропсы. Можно даже задать дефолтные высоту и ширину. 
4) Маркер премиум тоже можно рендерить просто через пропс ```isPremium```

2021-06-28 16:05 UTC, lula-may commented
Спасибо за ответ и за замечания! Надеюсь стало лучше))

2021-06-28 19:58 UTC, eoL95 commented on project/src/components/map/map.jsx
> +const defaultIcon = leaflet.icon({
константы по тех заданию нужно капсом именовать, но это нестрашно в вследующих пр починим

2021-06-28 19:58 UTC, eoL95 commented on project/src/const.js
> +  'cities': [260, 200],
тут тоже без ковычек именование, надо будет поправить

2021-06-28 19:59 UTC, eoL95 commented
Пулл реквест мержу, но эти мелкие замечания поправь пожалуйста в следующих заданиях

2021-06-28 19:59 UTC, merged